# Generated by Django 4.2 on 2023-04-28 15:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='item',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'title')},
        ),
    ]
