# Generated by Django 4.2 on 2023-04-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_item_favorite_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'user', 'verbose_name_plural': 'item'},
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='title',
            new_name='item',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
