# Generated by Django 4.2 on 2023-04-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Информация о заказах', 'verbose_name_plural': 'Информация о заказах'},
        ),
    ]
